name: Armada JS Battleship CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build --if-present
      
      - name: Test
        run: yarn test --if-present
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_DEPLOY_TOKEN }}
          
      - name: Deploy
        run: cd server/dist
